### ISSUE TITLE
HoneycombEventManager doesn't work in Hosted Services

### ISSUE THREAD

**Issue by taspeotis** [honeycombio/libhoney-dotnet#18] opened 2020-10-21 10:46 UTC
Hi,

`HoneycombEventManager` has an `AddData` method that does not work in all use cases, notably [hosted services](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services). Hosted services are part of ASP.NET Core so I would expect some way to work with them, even if the middleware can't do this automatically.

The problem is the dependence on `HttpContext` - there's no ambient request for background services.

I'd like to propose some changes, and my time permitting I'd implement it myself.

First, and most simply, I'd like `AddData` to have some tolerance for `HttpContext` being null.

Second, I'd like to decouple the creation of a `HoneycombEvent` from the middleware. It will still be done there, but via an API that other services could use. Notionally this would be something like a `new HoneycombEventScope(httpContext)` that is `IDisposable`. Upon being disposed it would automatically add timing information and enqueue itself to be sent.

The important thing is other consumers could create their own scopes from things other than HTTP requests, so if you had a background service you could do something like `new HoneycombEventScope(traceId)`.

Please note those are examples, it could be an `IHoneycombEventManager` or something once we get into the implementation.

If there's an appetite for these changes I can put together a pull request.

**Comment by martinjt** [comment] 2020-10-21 21:21
Would this be covered by using open telemetry? That's where most of the
effort is going, and looking at your descriptions, it sounds like thats
what you need with scopes etc.

I'd worry that this is doing more than the library was intended to do.  For
what you're suggesting I'd suggest a separate project that more versatile,
and then eventually have the AspNetCore project call into it.  The core
background service should still work with the IHoneycombService to send
events.

**Comment by taspeotis** [comment] 2020-10-22 07:30
Thanks for the quick reply. I was unaware of OpenTelemetry + Honeycomb working together. I'll take a closer look but I don't think I have the risk appetite for it at this stage<sup>1</sup>.

I have similar reservations to you about what is the scope of this library, but at the same time I feel the ASP.NET Core-bits of the library should work for ASP.NET Core background services.

What's your opinion on whether this library should support background services? Last night I was able to put together something I felt would work but was more complicated than I wanted it to be. Given the complexity of a general-purpose implementation I'm content to close this GitHub issue and roll-my-own background task stuff. It can still take advantage of the `HoneycombService` for sending and all that.

<sup>1</sup> <small>No discredit to what seems like an amazing amount of work people are putting it in to get it ready, but the OpenTelemetry .NET GitHub repo says:

> The library is not yet generally available, and releases aren't guaranteed to conform to a specific version of the specification. Future releases will not attempt to maintain backwards compatibility with previous releases. Each alpha and beta release includes significant changes to the API and SDK packages, making them incompatible with each other.

And the OpenTelemetry Operator for Kubernetes repo says:

> Until the OpenTelemetry Collector format is stable, changes may be required in the above example to remain compatible with the latest version of the OpenTelemetry Collector image being referenced. ... At this point, the Operator does not validate the contents of the configuration file: if the configuration is invalid, the instance will still be created but the underlying OpenTelemetry Collector might crash.

**Comment by MikeGoldsmith** [comment] 2021-03-05 15:47
We’re going to close this for now as we're moving more towards supporting OpenTelemetry SDKs. Feel free to re-open if it’s still relevant.

**Closed by MikeGoldsmith** 2021-03-05 15:47 UTC
